# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t_g14-_peMSkzmAFUFy_QTfhaCe8NdYI
"""

import numpy as np

a = np.genfromtxt('out.csv',delimiter=',',skip_header=True)
ematrix = np.eye(*a.shape)
res = np.dot(a, ematrix.transpose())
np.savetxt("new_out.csv", res, delimiter=",")